/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as MisTicketsSoporteRouteImport } from './routes/mis-tickets-soporte'
import { Route as MisTicketsRouteImport } from './routes/mis-tickets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrearTicketRouteImport } from './routes/crear-ticket'
import { Route as BandejaSoporteRouteImport } from './routes/bandeja-soporte'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MisTicketsSoporteRoute = MisTicketsSoporteRouteImport.update({
  id: '/mis-tickets-soporte',
  path: '/mis-tickets-soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const MisTicketsRoute = MisTicketsRouteImport.update({
  id: '/mis-tickets',
  path: '/mis-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearTicketRoute = CrearTicketRouteImport.update({
  id: '/crear-ticket',
  path: '/crear-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaSoporteRoute = BandejaSoporteRouteImport.update({
  id: '/bandeja-soporte',
  path: '/bandeja-soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bandeja-soporte': typeof BandejaSoporteRoute
  '/crear-ticket': typeof CrearTicketRoute
  '/login': typeof LoginRoute
  '/mis-tickets': typeof MisTicketsRoute
  '/mis-tickets-soporte': typeof MisTicketsSoporteRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bandeja-soporte': typeof BandejaSoporteRoute
  '/crear-ticket': typeof CrearTicketRoute
  '/login': typeof LoginRoute
  '/mis-tickets': typeof MisTicketsRoute
  '/mis-tickets-soporte': typeof MisTicketsSoporteRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bandeja-soporte': typeof BandejaSoporteRoute
  '/crear-ticket': typeof CrearTicketRoute
  '/login': typeof LoginRoute
  '/mis-tickets': typeof MisTicketsRoute
  '/mis-tickets-soporte': typeof MisTicketsSoporteRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bandeja-soporte'
    | '/crear-ticket'
    | '/login'
    | '/mis-tickets'
    | '/mis-tickets-soporte'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bandeja-soporte'
    | '/crear-ticket'
    | '/login'
    | '/mis-tickets'
    | '/mis-tickets-soporte'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bandeja-soporte'
    | '/crear-ticket'
    | '/login'
    | '/mis-tickets'
    | '/mis-tickets-soporte'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BandejaSoporteRoute: typeof BandejaSoporteRoute
  CrearTicketRoute: typeof CrearTicketRoute
  LoginRoute: typeof LoginRoute
  MisTicketsRoute: typeof MisTicketsRoute
  MisTicketsSoporteRoute: typeof MisTicketsSoporteRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-tickets-soporte': {
      id: '/mis-tickets-soporte'
      path: '/mis-tickets-soporte'
      fullPath: '/mis-tickets-soporte'
      preLoaderRoute: typeof MisTicketsSoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-tickets': {
      id: '/mis-tickets'
      path: '/mis-tickets'
      fullPath: '/mis-tickets'
      preLoaderRoute: typeof MisTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-ticket': {
      id: '/crear-ticket'
      path: '/crear-ticket'
      fullPath: '/crear-ticket'
      preLoaderRoute: typeof CrearTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja-soporte': {
      id: '/bandeja-soporte'
      path: '/bandeja-soporte'
      fullPath: '/bandeja-soporte'
      preLoaderRoute: typeof BandejaSoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BandejaSoporteRoute: BandejaSoporteRoute,
  CrearTicketRoute: CrearTicketRoute,
  LoginRoute: LoginRoute,
  MisTicketsRoute: MisTicketsRoute,
  MisTicketsSoporteRoute: MisTicketsSoporteRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
